#!/usr/bin/python2.7

import glob, sys, os, subprocess
from shutil import copyfile

print os.getcwd()

with open('Picofile') as picofile:
    for line in picofile:
        line = line.rstrip() # remove returns
        if line.startswith('NAME'):
            output = line.split()[1] + '.p8'

# make a copy of the assets.p8 file to use as the base
copyfile('src/assets.p8', output)

filenames = glob.glob('src/*.p8')

with open(output, 'a') as outfile:
    for fname in filenames:
        if fname!='src/assets.p8':
            with open(fname, 'r') as readfile:
                outfile.write('\n' + readfile.read())

if sys.argv[1]=='run':
    # command = '/Applications/PICO-8.app/Contents/MacOS/pico8 -run ' + output
    command = '/Applications/PICO-8.app/Contents/MacOS/pico8'
    print command
    subprocess.Popen(command)
