#!/usr/bin/python2.7

import glob, sys, os

output = os.path.basename(os.getcwd()) + '.p8' # name the final file whatever the parent folder is

filenames = glob.glob('src/*.p8') # get the .p8 files in the src directory

with open(output, 'w') as f:
    with open('src/_assets.p8') as r:
        for line in r:
            line = line.rstrip()
            if line != '':
                f.write(line + '\n')
            else:
                break
    for filename in filenames:
        if filename != 'src/_assets.p8':
            with open(filename, 'r') as r:
                f.write('\n' + r.read())
    with open('src/_assets.p8', 'r') as r:
        head = True;
        for line in r:
            line = line.rstrip()
            if head:
                if line == '':
                    head = False
                    f.write('\n')
            else:
                f.write(line + '\n')

if sys.argv[1]=='run':
    os.system("/Applications/PICO-8.app/Contents/MacOS/pico8 -run " + os.getcwd() + "/" + output)
